### ISSUE TITLE
Remove or keep targetAttributeType?

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/PostgreSQL-Table-Translation-Framework#118]
We could easily determine types of target attributes by checking the return types of translation functions.

That would eliminate possible conflicts between what's in the targetAttributeType column and the return type of the translation function and thus less errors in the translation tables and less things to validate.

**Comment by edwardsmarc** [comment]
I find it useful for writing the translation table. Without it it's not easy to find what the type is, user would need to look at the return type of the translation function which can sometimes only be found from the sql code.

Useful for checking error codes are of the correct type for example.

**Comment by pedrogit** [comment]
Another argument is that sometimes the user could want to impose a more precise type on the output then what is returned from the translation function e.g. translation function return integer (4 bytes) but the users wants bigint (8 bytes).

Hum. Maybe that's even not supported right now...

**Comment by pedrogit** [comment]
So we keep... Closing.
