### ISSUE TITLE
Make translation engine able to validate all the translation table attributes

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/PostgreSQL-Table-Translation-Framework#12]
That includes all the attributes other than validationRules and translationrule (those will be validated in issue #11).

**Comment by edwardsmarc** [comment]
In TT_ValidateTTable() not only check validation rule exists but also that there is a value for each column before processing anything

**Comment by edwardsmarc** [comment]
* #56 added checks that all attributes are not null or empty strings.

* Should we add more detailed checks?
  * e.g. for targetAttributeType we could check the value is a valid postgresql type (e.g. text, double precision, int).
  * e.g. for rule_id we could check value is an integer

**Comment by pedrogit** [comment]
I guess checking that targetAttributeType match the translation rule return type is sufficient.

Maybe we could check that the error code is a valid error code.

**Comment by edwardsmarc** [comment]
* #76 will check the error is of the correct type.
* @pedrogit Are you suggesting we also check the error code is present in a master list of acceptable error codes?
* If we do this I'd vote to make it optional so users have flexibility to make their own error code systems.

**Comment by pedrogit** [comment]
Right, error codes are application specific. We should have a way to validate them againt a list when validating the translation file. The question is how to implement this...

**Comment by edwardsmarc** [comment]
Maybe an optional argument to TT_Translate? Either an array or table of error codes to check against.

**Comment by pedrogit** [comment]
Maybe we don't have to. Error codes do not refer to anything else than themselves. So even if a wrong error code is provided, there is no impact on the rest of the logic (in opposition with values, parameters, null values and function names). It is up to the translation file writer to not make a mistake here.
