### ISSUE TITLE
TRANSLATION_ERROR should be configurable

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/PostgreSQL-Table-Translation-Framework#121]
What if -3333 is a possible valid value? There would be no way to distinguish a good value from a translation error. The user has to have a way to set another error value as he can do it for validation functions.

**Comment by edwardsmarc** [comment]
An additional column is the translation table?

Or we could add the (...|error) syntax to translation functions. This might make sense for consistency.

**Comment by pedrogit** [comment]
Yes the (...|error) syntax make everything smoother.

**Comment by edwardsmarc** [comment]
Steps to add error codes to translation rules:

- TT_ValidateTTable - add check that translation rule is not null or empty, and of the correct type.
- TT_Translate - Change returning of TRANSLATION_ERROR or -3333 to return (translationrow.translationrule).errorCode
- No changes needed to ParseRules(). The error code should just show up when added to the translation table.

**Comment by edwardsmarc** [comment]
Update: default values of TRANSLATION_ERROR and -3333 should be used if no error code is provided.
