### ISSUE TITLE
Rebuild string lists in the TextFctEval and pass to helpers

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/PostgreSQL-Table-Translation-Framework#122]
- String lists need to be parsed inside the helper function.
- So they need to get their values assigned in TextFctEval, then get wrapped in quotes and {} and passed to the helper function.
- Helper function will validate them as type stringList and parse them using ParseStringList.
- All values should be passed as single quoted strings inside {}. This way the existing ParseStringList function can unpack them as string values.

- e.g. translation syntax argument: {columnA, 'string1', 'string//2'}
- would get its values assigned: e.g. valA, string1, string//2
- and build them back to a stringList to pass to the helper function: {'valA', 'string1', 'string//2'}

**Comment by pedrogit** [comment]
You can write a TT_StringListAsString()..

**Comment by edwardsmarc** [comment]
What would TT_StringAsList() do?

So far I have done the following and everything works based on initial testing:

- Moved the trimming of {} into ParseStringList so it now accepts a text string wrapped in {}. It now checks the input text is wrapped in {}, i.e. a valid stringList.

- Added a strip argument to ParseStringList. 
  - If FALSE it returns col names as bare values and keeps any strings wrapped in quotes with their quotes. e.g. input {col_A, 'string1', 'string2'} becomes output array of col_A, 'string1', 'string2'. This is the required behaviour for parsing translation table arguments and passing them to TextFctEval. In this case we need the quotes to ID what is a string and what is a column name.
  - If TRUE it strips the quotes from any strings and returns an array of e.g. val_A, string1, string2. This is the required behaviour for parsing stringList arguments inside the helper functions where everything is processed as val::text. 

- Wrapped all return values for stringLists processed in TextFctEval in single quotes. Before it would get any column values and return {val1, val2, val2}. Now it returns {'val1', 'val2', 'val2'}. This means when ParseStringList is called inside the helper functions we can support special characters and commas inside strings.

- Added type stringList in helper function file.

- Added IsString() validation function to check string is wrapped in {}.

- Added validation for type stringList in TT_ValidateParams.

- Updated helper functions to validate stringList attributes and use TT_ParseStringList to unpack stringList arguments - incomplete - fix in #126

**Comment by pedrogit** [comment]
TT_StringListAsString() (or TT_RepackListAsString) is for isolating the code that repack the list of strings to a stringList string.

StringList become like an object on which we write methods (ParseStringList, RepackStringList, IsStringList, etc...). Object Oriented programming...

**Comment by pedrogit** [comment]
I see that stringList strings are repacked progrssively while the query is being built. So the way it is constructed now, we can not simply call a TT_StringListAsString()... We would have to build a list of string instead and pass it only at the end to TT_StringListAsString().

**Comment by edwardsmarc** [comment]
I'm changing it so TextFctEval when dealing with stringLists collects the strings or column values in an array, then repacks them to a stringList object using TT_RepackStringList. I've added a strip argument to either keep or discard the quotes from the input strings. For passing to the helper functions will will always discard these which is the default.

**Comment by pedrogit** [comment]
Why would you want to strip quotes when repacking?

**Comment by edwardsmarc** [comment]
When RepackStringList is run we are no longer dealing with column names and quoted strings. We are dealing with values. Values could be the input string, or could be the column value pulled from the source row.

Everything in the output stringList is therefore a string value to be passed to the helper function so there is no need for anything to maintain it's original quotes from the translation table.

This strip in RepackStringList is not strictly needed since we can do the strip in ParseStringList inside the helper function. Should I remove it for simplicity?

**Comment by pedrogit** [comment]
What if some  strings in the stringlist contains commas or quotes?

{'hi, let\'s go', 'string2'}

gets repack to

{hi, let\'s go, string2}

How the parser, when called from the helper function, will parse that?

**Comment by edwardsmarc** [comment]
You're correct. Which raise's the question what if a column value has special characters or spaces. I guess we should wrap everything in single quotes for repacking?

Which means this function will only be useful for passing values from the engine to the helper function. It won't be able to repack column names.
