### ISSUE TITLE
Validate stringLists inside helper functions

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/PostgreSQL-Table-Translation-Framework#123]
**Create stringList type for helper functions, and TT_IsStringList, and add to TT_ValidateParams**

- Needed so stringLists can be validated at the start of each helper function.
- Inside the helper function we can test if the parameter is a valid stringList by adding this type (strinList) to TT_ValidateParams().
- We'll need a TT_IsStringList
- The idea is to treat stringList as any other type (integer, double precision, boolean, geometry)

- So two principle here:
1) All parameters accepting stringList are only treated as stringList (not as string)
2) stringList are treated and validated like normal types (integer, double precision, boolean, geometry)

**Comment by pedrogit** [comment]
Validating strinlist in TT_IsStringList() only with '{.+}' is certainly not sufficient. 

{'aa}

pass this test and is certainly not a valid stringlist...

**Comment by edwardsmarc** [comment]
Replaced with #133
