### ISSUE TITLE
Adapt most validation helper functions to accept many attributes

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/PostgreSQL-Table-Translation-Framework#13]
e.g. TT_NotNull() should be able to take a queoted list of attribute name. notNull("att1, att2, att3")

* Make VARIADIC

**Comment by edwardsmarc** [comment]
Functions made VARIADIC for beta version:
* NotNull
* NotEmpty
* IsInt
* IsNumeric
* IsString

ToDo in phase 2
* Between
* GreaterThan
* LessThan
* HasUniqueValues
* Match
