### ISSUE TITLE
TT_GeoIntersectionText() is failing when the number of row is high

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/PostgreSQL-Table-Translation-Framework#137]
How is the performance affected by the creation of temporary tables VS looping over results to determine the correct result?

**Comment by edwardsmarc** [comment]
What's the benefit of using the **$1** syntax in the query string and **FOR geoRow IN EXECUTE query USING _the_geom LOOP**?

As opposed to to replacing **$1** with **_the_geom** when building the query string?

**Comment by pedrogit** [comment]
- it prevents problems that could arise with quotes and character escaping.
- it prevents having to cast non text objects (like integers, float, raster and geometries) to text only to have to recast them back to their original type inside the query.
- it's more "SQL" in the sence that the possiblity to do it using the language exist so we should use the features of the language as much as possible.
