### ISSUE TITLE
TT_IsStringList() should return TRUE when the stringlist is only a string

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/PostgreSQL-Table-Translation-Framework#153]
But that make helperFunctionTest to fail some test. To revisit.

**Comment by pedrogit** [comment]
Must work for 

matchList(src_filename, {'Forest'}|INVALID_VALUE);

**Comment by edwardsmarc** [comment]
SELECT TT_IsStringList('str') returns TRUE. Is this the desired behavior? 

Reason is that TT_ParseStringList now works for both string lists (e.g. {'1','2','3'}) and strings (e.g. '1').

Originally TT_IsStringList was meant to identify strings surrounded in {}.

**Comment by pedrogit** [comment]
Treating simple strings as a particular case of stringlists greatly simplyfy the engine code. Now we simply loop over stringlists.
