### ISSUE TITLE
Add AllNotNull() and AllNull()

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/PostgreSQL-Table-Translation-Framework#156]
Need function to return true if all values are not null - AllNotNull()

Need function to return true if all values are null - AllNull()

The combination of these two can probably replace NotNULLEmptyOr

**Comment by pedrogit** [comment]
Why AllNotNull() and AllNull()?

**Comment by pedrogit** [comment]
AllNotNull() is TT_NotNull() accepting a stringlist.

**Comment by edwardsmarc** [comment]
Is there any reason not to make TT_NotNull() accept a string list? If one value was supplied it would work as it does now. If a string list was provided it would evaluate if all values are not null.

Two use cases would be:

NotNull(val1); NotNull(val2) - this would test val1 first, if TRUE val2 would be tested.

NotNull({val1, val2}) - this would test if both val1 and val2 are not null.


We could make IsNull() using the same format (instead of AllNull()).

**Comment by pedrogit** [comment]
That was my point...

**Comment by edwardsmarc** [comment]
I've attempted to make NotNull accept string lists. Can you review it @pedrogit?

Also, any ideas how to test if all elements of the array are NULL? Might need to EXECUTE a query for that one.

**Comment by edwardsmarc** [comment]
Closed with 61850a1cf90c5c829d5fde45565a875267d193f6

**Comment by pedrogit** [comment]
I guess there should be 

    -- validate source value (return FALSE)
    IF NOT TT_IsStringList(val) THEN
      RETURN FALSE;
    END IF;

at the beginning to make sure stringlist is well formed before parsing it. Look at TT_NotNULLEmptyOr()
