### ISSUE TITLE
Add countNotNulls() validation function

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/PostgreSQL-Table-Translation-Framework#159]
In some cases where translation requires multiple columns, a specific number of non-null values is required. For example one translation requires that only one of two columns has a value. The other column should always be null. We have NotNullEmptyOr() that tests for at least one notNull value. This can solve our test case for two columns but not more.

countNotNulls(stringList, count)

stringList - string list of values to test
count - expected number of notNull values

If the number of notNull values is equal to the count variable, return true. Otherwise return false.

**Comment by pedrogit** [comment]
NotNullCount()? to follow NotNullEmptyOr()

**Comment by edwardsmarc** [comment]
It could probably replace NoNullEmptyOr() if we added an 'exact' flag. We could then test these cases:

NotNullCount('{val1, val2, NULL}', 2, exact=TRUE) - exactly two of three columns has values
NotNullCount('{val1, val2, NULL}', 1, exact=FALSE) - at least one of three columns has values. This is equivalent to NotNullEmptyOr().
