### ISSUE TITLE
Engine targetAttributeList parameter might not be necessary

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/PostgreSQL-Table-Translation-Framework#16]
targetAttributeList was originally intended to get the engine to check, before starting a potentially long translation, that the list of attribute defined in the translation table matches the list of attribute of an existing target table we want to append to. This is still useful if processed rows are appended to the target table only at the end of the process, which would produce an error way too late. If the error is signaled by postgresql at the beginning of the process then we might want to get rid of this eventual useless parameter. Only test will determine that.

In brief, we want to make sure, in the two following scenarios, that we are properly warned when the attribute list in the second translation table does not match the attribute list of the first translation:

-- Scenario A
SELECT TT_Prepare('translation', 'ab06_avi01_lyr', '_ab06');
CREATE TABLE casfri50.lyr_all AS
SELECT * FROM TT_Translate_ab06('rawfri', 'ab06_test', 'translation', 'ab06_avi01_lyr');

SELECT TT_Prepare('translation', 'ab16_avi01_lyr_test', '_ab16');
INSERT INTO casfri50.lyr_all 
SELECT * FROM TT_Translate_ab16('rawfri', 'ab16_test', 'translation', 'ab16_avi01_lyr_test');

or 

-- Scenario B
SELECT TT_Prepare('translation', 'ab06_avi01_lyr', '_ab06');
SELECT TT_Prepare('translation', 'ab16_avi01_lyr_test', '_ab16');
CREATE TABLE casfri50.lyr_all AS
SELECT * FROM TT_Translate_ab06('rawfri', 'ab06_test', 'translation', 'ab06_avi01_lyr');
UNION ALL
SELECT * FROM TT_Translate_ab16('rawfri', 'ab16_test', 'translation', 'ab16_avi01_lyr_test');

In scenario A there is a risk that the second translation is compatible with the first even if some attributes are missing (e.g. if you just forget the last attribute or if all attribute are of the same type (int) and some are lacking).

Scenario B is less riscky as PostgreSQL would refuse to union two tables having a different number of attribute or if they are not of the same types. However scenario B is not the prefered way to merge two translated tables because everything will fail as soon as one error is found in one translation table. It could for example take 2 hours to process the first SELECT just to have PostgreSQL trow everything to the garbage because of a small error in ab16_avi01_lyr_test. 2 hours wasted.

So better have a solution that ease and secure scenario A...

**Comment by pedrogit** [comment]
Only checking the names is not sufficient. The type of each target attribute is actually more important.

A query attempting to append a translated table having a list of wrongly typed attribute will fail straight at the beginning with a message like:

ERROR:  column "height_lower" is of type integer but expression is of type text

**Comment by pedrogit** [comment]
We could however provide a TT_AttNamesAndTypes() helper function that would produce the list of attribute names and types for a previously produced table and use this function whem calling the engine which could then verify that the current translation table matches those names and types... This is full security at low cost.

**Comment by pedrogit** [comment]
In scenario B, the query would fail because of mismatching types before types are checked by solution 4. However this solution would work fine in scenario 1 which should be the prefered way to append large translated tables to each other.

**Comment by edwardsmarc** [comment]
Why is it "impossible to append two translation to the same table in the same query" under scenario A? Isn't scenario A always translating and appending one table at a time. Couldn't you just provide casfri50.lyr_all to check the names and types of all subsequent INSERTs?

**Comment by pedrogit** [comment]
Yes, solution 3 works in case of Scenario A. But not in case of scenario B. That's why I think Solution 4 is better. It works in both scenarios. It's nice that it work in case of Scenario B even if this scenario is not the privileged one.

**Comment by edwardsmarc** [comment]
I agree on solution 4. And putting the validation in TT_Prepare makes sense, that way you could run all your TT_Prepare statements and know that the append will work before running any translations.

**Comment by pedrogit** [comment]
Forgot to remove the targetAttributeList parameter from _TT_Translate()
