### ISSUE TITLE
TT_FctEval() - Revisit the way we convert helper function parameters to types to identify function from the PG catalog.

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/PostgreSQL-Table-Translation-Framework#17]
Right now we "guess" the types but there is no garantee that they will match actual helper function types. this could quickly result in some helper funtion being considered invalid. A better approach would be to just make sure that guessed types are compatible with actual function parameter types.

The actual exact matching might force us to write one helper function per type. e.g. notNull(int), notNull(text), etc rather than a more simple generic notNull(anyelement).

**Comment by edwardsmarc** [comment]
@edwardsmarc to look at code and make proposal for review.

**Comment by edwardsmarc** [comment]
* Change TT_fctExists engine function to check for helper function names and number of parameters.
* Could look in catalog or look in a hard coded array of function names and number of paramters (expected signatures would be hard coded in function). We prefer the catalog method because it reflects whats loaded. Requires looking in catalog and grabbing name and number of parameters for each helper function. Then takes translation function, maches the name and checks number of paramters is correct.
* If function doesn’t exist, engine stops and returns error to user.

**Comment by edwardsmarc** [comment]
Update, validation helper functions should accept only text, translation helper functions should accept and return the correct value type. Signatures for translation helper functions will therefore need to be checked, likely by calling the function to see if it exists, Option D here: https://github.com/edwardsmarc/PostgreSQL-Table-Translation-Framework/blob/master/doc/fctexists.md

**Comment by edwardsmarc** [comment]
Proposal for review by @pedrogit ...

* Rename current TT_FctExist, TT_FctSignature, TT_FctEval to TT_FctExist2, TT_FctSignature2, TT_FctEval2 so we have them intact for future use if needed.

* Edit TT_FctSignature so it no longer guesses argument types using TT_Guess. Instead it simply takes the array of n arguments from the translation table and returns an array of 'text' repeated n times. Output array is used in TT_FctExists as argTypes.

* Edit TT_FctExist (takes inputs fctName and argTypes) to lookup the function signature in pg_proc using the following query:
SELECT count(*)
    FROM pg_proc
    WHERE oid::regprocedure::text = fctName || '(' || array_to_string(TT_LowerArr(argTypes), ',') || ')'
    INTO cnt;

**Comment by pedrogit** [comment]
I would suggest to only create a new TT_FctExists() (TT_TextFctExists) function taking the function name of the function and the number of (text) arguments (taken directly from the length of the args array when calling it). It can both build the complete signature itself and check for it's existence.

**Comment by edwardsmarc** [comment]
This is working, one catch is that every helper function needs to have its signature explicitly defined in the catalog. So any helper functions using a DEFAULT parameter need to be written as two signatures where the simpler function calls the full function. e.g. greaterThan(5, 1) calls greaterThan(5, 1, TRUE).

**Comment by edwardsmarc** [comment]
Closing. Made new TT_TextFctExists and TT_TextFctEval functions. Removed DEFAULT assignments from helper functions and added second signature when default parameters required.
