### ISSUE TITLE
TT_IsNull() and TT_NotNullEmptyOr() are not used anymore

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/PostgreSQL-Table-Translation-Framework#173]
Should we get rid of them? Could they be still useful in another translation project? Were they replaced by another more useful function?

**Comment by pedrogit** [comment]
I marked them DEPRECATED in the documentation. We should still get rid of them if we found better ways to achieve the same goal.

**Comment by pedrogit** [comment]
Marc, can we get rid of them?

**Comment by edwardsmarc** [comment]
They are no longer needed since we added acceptNull #157 
We can get rid of them.
