### ISSUE TITLE
Make TT_NotMatchList()

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/PostgreSQL-Table-Translation-Framework#179]
Anything matching the list returns FALSE. Inverse of matchList().

Just add a 'match' hidden parameter to matchList() defaulting to TRUE. notMatchList() would then just be a wrapper around matchList() passing it FALSE inversing the logic.

**Comment by MelinaHoule** [comment]
I just changed the class for error type unused value from Missing to Invalid in the documentation as discussed. I had to change the numeric code to fit the others invalid numeric code. See 7b7f61e.
The numeric error code for unused value is now -9994 instead of -8885.
