### ISSUE TITLE
Write GitHub readme for translation engine

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/PostgreSQL-Table-Translation-Framework#19]
Will be used for March 31 progress report

Proposed structure
* Intro
* Directory structure
* Requirements - software versions
* Installation/uninstallation - version releases
  * Test scripts
* How to write translation table
* Code example - example of running engine.
  * Use test tables to write examples
  * Develop vocabulary - target tab, source tab etc.
* List of helper functions and what they do. Document different variants.
* Adding custom helper functions
* Credits

**Comment by pedrogit** [comment]
So what should go in this file? What's the normal structure of a readme file?

**Comment by pedrogit** [comment]
Some inspiration for readme:

https://gist.github.com/PurpleBooth/109311bb0361f32d87a2

https://trac.osgeo.org/postgis/browser/trunk/README.postgis

https://www.makeareadme.com/

https://medium.com/@meakaakka/a-beginners-guide-to-writing-a-kickass-readme-7ac01da88ab3
