### ISSUE TITLE
Review all helper functions parameter and return value types

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/PostgreSQL-Table-Translation-Framework#20]
1) When does a function should be accepting anyelement?
2) When does a function should be returning anyelement?
3) Should validation functions be able to return NULL and ""? Maybe not...
4) When does a function should be just a sql wrapper around a PL/pgSQL one?
5) Should translation functions be able to return NULL?

**Comment by pedrogit** [comment]
- All of them should definitely return only TRUE or FALSE. Because NULL is not an INT, not between  X an Y, etc... Other wise we leave the burden of deciding what to do with a null to the function user.
- More comments to come...

**Comment by edwardsmarc** [comment]
@pedrogit 
* So TT_Between(Null, 0, 100) will return False.
* What if the function itself is not valid? Should that also return False because the True condition has not been met?
* e.g. TT_Between(10, 0, Null).

**Comment by pedrogit** [comment]
Should it raise an error in the first case?

I Would say it is more than empty. So false.

**Comment by edwardsmarc** [comment]
Yes, in the first case the user has clearly made a mistake in the translation table so raising an error would be logical. I'll set NotEmpty(Null) to return False and we can revisit the decision if needed once we are testing.

**Comment by edwardsmarc** [comment]
To decide: should variadic be removed from all validation functions? Would mean translation table would call NotNull(var1) NotNull(var2) instead of NotNull(var1, var2). Variadic causes trouble with translation engine validation code.

**Comment by pedrogit** [comment]
I removed the problematic code so now variadic functions work.

I would replace it by the non variadic one in the CASID case not because it does not work but because it would make the error code more meaningfull.

However that's maybe an indice that there are not a good idea. And I have no idea how I'm going to validate them.

I would vote to let them for he beta and see after.

**Comment by pedrogit** [comment]
Here is a more complete list of rules to be applied after the beta.

Some definitions: 

- source value: value to be tested by a validation helper function or used by a translation helper function.
- parameter: all values passed to the helper function which is not a source value.

Rules:

- All helper functions should raise an exception when any parameter (other than the source value) is null or of an invalid type. So there is no need to implement variants that take parameter of a type other than the proper type for this parameter. e.g. TT_Between(text, text, text)

- All helper functions should have a variant minimally accepting a text source value. 

- All helper functions should test for NULL and return FALSE when the the source value is NULL.

- No helper function should be implemented as VARIADIC accepting an arbitrary number of parameters. If an arbitrary number of parameters must be supported, it should be supported as list of value passed as a text value separated by a comma or a semicolon.

**Comment by edwardsmarc** [comment]
Closing, refer to readMe for helper function rules.
