### ISSUE TITLE
Write tt_max, tt_min, tt_minIndexCopyText, tt_maxIndexCopyText, tt_minIndexMapText, tt_maxIndexMapText, tt_minIndexNotNull, tt_maxIndexNotNull

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/PostgreSQL-Table-Translation-Framework#208]
* tt_max({1990, 2000}) -- returns 2000 - return max value.
* tt_min({1990, 2000}) -- returns 1990 - return min value.
* tt_minIndexCopyText({1990, 2000}, {a, b}) -- returns a - return the value from the second list matching the index of the smallest value from the first list.
* tt_maxIndexCopyText({1990, 2000}, {a, b}) -- returns b - return the value from the second list matching the index of the largest value from the first list.
* tt_minIndexMapText({1990, 2000}, {a, b}, {a,b,c,d}, {aaa, bbb, ccc, ddd}) -- returns aaa - Run mapText using the value from the second list matching the index of the smallest value from the first list.
* tt_maxIndexMapText({1990, 2000}, {a, b}, {a,b,c,d}, {aaa, bbb, ccc, ddd}) -- returns bbb - Run mapText using the value from the second list matching the index of the largest value from the first list.
* tt_minIndexNotNull({1990, 2000}, {null, b}) -- returns FALSE - Run notNull() on the value in the second list matching the index of the smallest value in the first list.
* tt_maxIndexNotNull({1990, 2000}, {null, b}) -- returns TRUE - Run notNull() on the value in the second list matching the index of the largest value in the first list.

**Comment by edwardsmarc** [comment]
@pedrogit :

Tests associated with TT_TestNullAndWrongTypeParams fail for TT_MinIndexMapText and TT_MaxIndexMapText.

Having reviewed the query built by the TT_TestNullAndWrongTypeParams for validating arguments, I don't think TT_TestNullAndWrongTypeParams can handle the format of TT_MinIndexMapText and TT_MaxIndexMapText. These functions have two arguments of source vals passed as string lists. It looks like the validation query is built with a single source val.

I don't think validation in this case is that important since the only arguments being validated are just passed to TT_MapText() inside the function. Those arguments have already been validated in the tests for TT_MapText().

**Comment by pedrogit** [comment]
Right. TT_TestNullAndWrongTypeParams() is made for functions taking only one source value and it does not accept NULL as valid parameters. In this case your would have to write your own tests for NULL and invalid parameters.
