### ISSUE TITLE
Add return value for each function examples in the documentation

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/PostgreSQL-Table-Translation-Framework#226]
Examples like:

e.g. MaxIndexCopyText({1990, 2000}, {burn, wind})

Are not fully helpfull if we do not indicate what the return value is supposed to be. In this case we should add it at the end of the line as a SQL comment:

e.g. MaxIndexCopyText({1990, 2000}, {burn, wind}) -- returns 'wind'

**Comment by edwardsmarc** [comment]
Done
