### ISSUE TITLE
Make function documentation template

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/PostgreSQL-Table-Translation-Framework#23]
* Template for documenting functions, similar to https://www.postgresql.org/docs/9.1/sql-createfunction.html
* Each function page will be hyperlinked from readMe

**Comment by pedrogit** [comment]
For now I would not document the functions more than what is found in the helperFunction.sql file. I would only make a list of them in the readme with a short description. They might change drastically after we fix #20 and #17..
