### ISSUE TITLE
Check STABLE and IMMUTABLE

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/PostgreSQL-Table-Translation-Framework#230]
Which helper functions should be STABLE and which should be IMMUTABLE?

Currently some functions that use lookup tables are set to STABLE. Should all of these be set to STABLE.

For the purposes of the engine, what is the difference between STABLE and IMMUTABLE?

**Comment by pedrogit** [comment]
https://dba.stackexchange.com/questions/185044/postgresql-immutable-volatile-stable 

provides a good explanation of IMMUTABLE, STABLE vs VOLATILE.

https://www.postgresql.org/docs/11/xfunc-volatility.html 

is more detailed.

IMMUTABLE, STABLE and VOLATILE define the volatility of a function in respect to the values it returns. IMMUTABLE functions always return the same value whatever the inputs (so the planner can reuse the value computed once if the function is called more than once in a query). VOLATILE  functions don't. STABLE function are kind of in-between.

All functions that refer to another table should be STABLE. Function volatility is used by the PostgreSQL planner to optimize queries.
