### ISSUE TITLE
Write alphaNumericMatchList()

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/PostgreSQL-Table-Translation-Framework#241]
e.g. alphaNumericMatchList(code, {'xx000', 'xx0', 'xx00xx00', 'xx0xx0', 'xx00xx00xx00', 'xx0xx0xx0'})

Converts code to alpha numeric string by replacing letters a-z to 'x', and integers 0-9 to '0'. Then runs tt_matchList to check if the converted alpha numeric string is in the list.

**Comment by pedrogit** [comment]
That looks like a regular expression match:

`SELECT 'xx0xx0xx0' ~ '^([a-z]{2}[0-9]{3}|[a-z]{2}[0-9]|([a-z]{2}[0-9]){2}|([a-z]{2}[0-9]{1,2}){3})$'`
