### ISSUE TITLE
Categorizing functions into helper and translation

### ISSUE THREAD

**Issue by prvernier** [edwardsmarc/PostgreSQL-Table-Translation-Framework#28]
Due to the increasing number of functions being developed, it might be a good idea to split them into 2 categogies: helper functions and translation functions. Each type of function would have a unique prefix, for example TT_h and TT_t.

**Comment by edwardsmarc** [comment]
We decide not to do this.

**Comment by pedrogit** [comment]
I created two clearly distinct sections in the readme.
