### ISSUE TITLE
Get the engine to always create target tables with attributes in the same order as in the translation table

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/PostgreSQL-Table-Translation-Framework#36]

**Comment by pedrogit** [comment]
Right now we use ocg.fid but it should only be the default (what if it does not exists?). It should be a parameter.
Also review everywhere where the translation is queried to make sure the order is applied.

**Comment by edwardsmarc** [comment]
We should add a row_id column to the translation table.

**Comment by edwardsmarc** [comment]
* ogc_fid should be replaced with rule_id in TT_ValidateTTable.
