### ISSUE TITLE
Make the engine to support single quoted strings present in the translation file

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/PostgreSQL-Table-Translation-Framework#37]

**Comment by edwardsmarc** [comment]
What is the goal of this issue? Can you provide an example of what needs to be supported?

* Currently the engine supports functions accepting comma separated strings in single quotes where the helper function uses the strings in the function. TT_Map is an example of this:
  * TT_Map(moist_reg, 'a,A,d,D,m,M,w,W', 'A,A,D,D,F,F,W,W')

* The engine does not currently support column names supplied in comma separated strings. Issue #52 will address this.

**Comment by edwardsmarc** [comment]
* This issue might have been done with #52.

**Comment by pedrogit** [comment]
Can we do copy('test 1') as a translation rule? If yes then we are fine.
