### ISSUE TITLE
Error when testing engine (TT_Translate) - all inventories

### ISSUE THREAD

**Issue by prvernier** [edwardsmarc/PostgreSQL-Table-Translation-Framework#45]
The sample workflow works well until the TT_Translate line. This is the case for all inventories. The following message appears e.g., NB01:

NOTICE:  _TT_Translate BEGIN
CONTEXT:  PL/pgSQL function _tt_translate(name,name,name,name,text[],boolean,integer,boolean,boolean) line 18 at RAISE
PL/pgSQL function tt_translate_nb01(name,name,name,name,text[],boolean,integer,boolean,boolean) line 3 at RETURN QUERY
NOTICE:  _TT_Translate 11 sourcerow={"im": null, "lc": null, "vt": null, "wc": null, "fst": 1, "plu": null, "slu": null, "wri": null, "l1cc": 4, "l1dc": 2, "l1ds": "I", "l1ht": 17, "l1s1": "SM", "l1s2": "YB", "l1s3": "TH", "l1s4": "BI", "l1s5": "SW", "l1sc": 2, "l1vs": 2, "l2cc": 0, "l2dc": 0, "l2ds": null, "l2ht": 0, "l2s1": null, "l2s2": null, "l2s3": null, "l2s4": null, "l2s5": null, "l2sc": 0, "l2vs": 0, "name": null, "spvc": null, "voli": null, "voln": 0, "wloc": null, "l1acs": 0, "l1cci": 0, "l1ds1": "I", "l1ds2": "I", "l1ds3": "I", "l1ds4": "M", "l1ds5": "M", "l1pr1": 3, "l1pr2": 2, "l1pr3": 2, "l1pr4": 2, "l1pr5": 1, "l1trt": null, "l2acs": 0, "l2cci": 0, "l2ds1": null, "l2ds2": null, "l2ds3": null, "l2ds4": null, "l2ds5": null, "l2pr1": 0, "l2pr2": 0, "l2pr3": 0, "l2pr4": 0, "l2pr5": 0, "l2trt": null, "sitei": null, "datayr": 2004, "l1funa": "TOHW", "l1orig": null, "l1trti": null, "l2funa": null, "l2orig": null, "l2trti": null, "nbwlid": null, "status": null, "stdlab": 41635230, "datasrc": "INTERP", "harv_id": null, "l1estyr": 0, "l1stock": 0, "l1trtyr": 0, "l2estyr": 0, "l2stock": 0, "l2trtyr": 0, "lic_key": null, "ogc_fid": 168697, "thin_id": null, "interpid": 0, "objectid": null, "plant_id": null, "water_id": null, "wlpolyid": null, "shape_len": 1540.115484, "buffer_cod": null, "shape_area": 62727.7802, "shape_leng": null, "water_code": null, "water_name": null, "src_filename": "Forest", "wkb_geometry": "010600002032BF0D000100000001030000000100000069000000F94267D9C1FE404132C907F39C4B30414EFD7788B6FE4041C3818420564B3041F14BD591B6FE40414024C442454B304183EE02C4B5FE4041AF6FBEF73A4B3041ED0B8C83B3FE40414A967A802E4B3041DE3993FEAFFE4041E931DC28264B3041C4DCC848AEFE40414F3357041E4B3041F3BD66C4ACFE4041F45611C1FE4A304159624F2DADFE4041DAD48B00F34A3041D1744400ADFE4041EE1E35CDEA4A30410B23C632AEFE404143DD86D6DE4A304108B5509EB1FE40413C69F589D74A30418C835BA5B6FE40411FCD8185D34A3041A98ED7FDBAFE4041E4C8323AD34A3041E29CA3ABC3FE40419E5221FDD64A3041F6D9504DC4FE4041CCBA8BF2CF4A3041FE762024C4FE40412E3815ACC34A304133E74A2EC2FE4041CFD175C0B74A304150954BA8C0FE4041D22069DFB34A3041F5D1A870BAFE404123D1746BA94A30418C55B506B8FE40419376E16EA74A3041A6CFE3F7B0FE404151C7A68DA34A3041CE79784BA9FE4041BF9844EA9F4A30418AF63BE6A6FE404187295A65A64A30411E39DBACA1FE4041731A6698A54A304114A812A691FE4041BBF708B0944A304102F5BBBD92FE404166B100EE994A30411B645DE192FE40418BF2C748AA4A304179F14CD595FE4041D4EF4B0ABC4A30411202788095FE4041F97EE144C84A30412A898B2394FE4041F2E1E842D04A3041BCCC0F1790FE404144D2B3A6D14A3041BD0E875C88FE4041609E803BD14A3041DE7ADF8684FE4041BD1F493AD04A30413FE0382D7DFE404101F07E7DC94A30419C9279E177FE4041B0AA1971C64A30418940B13773FE40410D83AD41C74A3041B09C72D66FFE4041F367D923CC4A3041AC97F7D371FE404178C0C4F2D44A304109DBC67275FE40418450BE26DF4A304145E5D92F78FE40413EEFEE2AE44A30419563408282FE40414BAD3398EF4A30412DD14C4880FE4041A617EA19F94A3041B311FB6A7CFE40416F22ABA8034B30413B5A5A7577FE40416EB93B7F0D4B304161A28F6A7AFE4041490CA129204B3041F81E382975FE4041FCE68723694B3041F243030D5FFE40414DC154CAA34B3041024AB35D5BFE4041E019878EAD4B304197DBC6D359FE404174ED09A5B14B3041718AC3E256FE4041E6FCA6F0B34B304165238A9A52FE4041685B0348B74B3041FE1B3FE352FE4041F42EC667B74B3041AC9717A553FE4041522F28EEBB4B3041C86DA8F852FE404108881F63C24B30410EF8A03F50FE404116167603CE4B3041C88E5C6E4DFE40418E72DA5ED74B304147C0314249FE4041B9341454DF4B3041864D006345FE4041E27EF545E04B3041E5CC157142FE4041EC62FDFBE04B30413E2ABDAE3BFE4041FB374F33E14B304106BC349237FE4041E01E3A9FE34B3041366A294332FE404154FAD901F24B3041174010CB2FFE4041B458D482F64B3041EF023BF92AFE40414B853ED0FB4B3041BD1F962724FE4041C60F747AFD4B3041E88ED55E1EFE404110FD3AD3054C304141D40B792AFE40412797093E124C3041A68BB39F33FE40411F1472B7194C3041E7D3870539FE4041A6D14B501F4C3041B5B9980C48FE4041652CC802354C304186012A734EFE40410501ACA23F4C30415456EDE350FE404110BA735F444C30412DDAAA4755FE40412029FF4A554C3041A2D0C1AF5DFE4041576D62144A4C30412B9B026163FE4041174B6873484C304179C2AAC369FE40415AE73C85494C30417025FC486CFE4041C4BF5DEE4A4C3041DE6E62526FFE40414C309CF44C4C3041249D8C9C75FE404139A6AD84534C3041A05BA5DB7FFE4041AAF8C8D4654C304108C4268C85FE4041C3E667EB724C30412F506CF689FE404144823127784C304119B3F7938FFE40419C66CCC95D4C30416EAAE4F590FE4041AA85CC8B4C4C3041502215BF92FE4041A9D0D8F33E4C304197AFF8CF98FE4041BA6C58A42C4C3041BEFD11369AFE40412E06B668274C30414B7395E79AFE4041295CA00F224C30412FCFA1DC9AFE404110C1F87A184C3041585E061D9AFE4041EEBD9753154C30417F06D54490FE4041DC0866D9F94B30418EE3E92B8EFE40415EB23034EE4B3041388A72108EFE404147809AA7E24B3041B177C5958FFE4041155F5116D24B3041FCCAA46B91FE40411BF81344C74B3041B3E1D35594FE404127C5DDAFBE4B304108CE2FBB98FE4041E3F0FEB5C14B3041488585B19EFE4041C371633DC84B30413852DD42A5FE4041EE2CB042C54B3041DB67F5ADADFE404182B24A5EBF4B30417719EE49B3FE4041507974D8B94B3041ECC5CEC8B8FE40414A89DB5EB14B304153CE7DCDBDFE4041BCD9EDE4A44B3041F94267D9C1FE404132C907F39C4B3041"}
CONTEXT:  PL/pgSQL function _tt_translate(name,name,name,name,text[],boolean,integer,boolean,boolean) line 22 at RAISE
PL/pgSQL function tt_translate_nb01(name,name,name,name,text[],boolean,integer,boolean,boolean) line 3 at RETURN QUERY
NOTICE:  TT_ValidateTTable BEGIN
CONTEXT:  PL/pgSQL function tt_validatettable(name,name) line 7 at RAISE
PL/pgSQL function _tt_translate(name,name,name,name,text[],boolean,integer,boolean,boolean) line 25 at FOR over SELECT rows
PL/pgSQL function tt_translate_nb01(name,name,name,name,text[],boolean,integer,boolean,boolean) line 3 at RETURN QUERY
NOTICE:  TT_ValidateTTable 11
CONTEXT:  PL/pgSQL function tt_validatettable(name,name) line 12 at RAISE
PL/pgSQL function _tt_translate(name,name,name,name,text[],boolean,integer,boolean,boolean) line 25 at FOR over SELECT rows
PL/pgSQL function tt_translate_nb01(name,name,name,name,text[],boolean,integer,boolean,boolean) line 3 at RETURN QUERY
NOTICE:  TT_ValidateTTable 22
CONTEXT:  PL/pgSQL function tt_validatettable(name,name) line 16 at RAISE
PL/pgSQL function _tt_translate(name,name,name,name,text[],boolean,integer,boolean,boolean) line 25 at FOR over SELECT rows
PL/pgSQL function tt_translate_nb01(name,name,name,name,text[],boolean,integer,boolean,boolean) line 3 at RETURN QUERY
NOTICE:  TT_ValidateTTable 33 query=SELECT * FROM translation.nb01_nbi01_lyr_test ORDER BY ogc_fid;
CONTEXT:  PL/pgSQL function tt_validatettable(name,name) line 18 at RAISE
PL/pgSQL function _tt_translate(name,name,name,name,text[],boolean,integer,boolean,boolean) line 25 at FOR over SELECT rows
PL/pgSQL function tt_translate_nb01(name,name,name,name,text[],boolean,integer,boolean,boolean) line 3 at RETURN QUERY
NOTICE:  TT_ValidateTTable 44
CONTEXT:  PL/pgSQL function tt_validatettable(name,name) line 20 at RAISE
PL/pgSQL function _tt_translate(name,name,name,name,text[],boolean,integer,boolean,boolean) line 25 at FOR over SELECT rows
PL/pgSQL function tt_translate_nb01(name,name,name,name,text[],boolean,integer,boolean,boolean) line 3 at RETURN QUERY

ERROR:  type of parameter 18 (character varying) does not match that when preparing the plan (text)
CONTEXT:  PL/pgSQL function tt_validatettable(name,name) line 21 at assignment
PL/pgSQL function _tt_translate(name,name,name,name,text[],boolean,integer,boolean,boolean) line 25 at FOR over SELECT rows
PL/pgSQL function tt_translate_nb01(name,name,name,name,text[],boolean,integer,boolean,boolean) line 3 at RETURN QUERY
********** Error **********

ERROR: type of parameter 18 (character varying) does not match that when preparing the plan (text)
SQL state: 42804
Context: PL/pgSQL function tt_validatettable(name,name) line 21 at assignment
PL/pgSQL function _tt_translate(name,name,name,name,text[],boolean,integer,boolean,boolean) line 25 at FOR over SELECT rows
PL/pgSQL function tt_translate_nb01(name,name,name,name,text[],boolean,integer,boolean,boolean) line 3 at RETURN QUERY

**Comment by prvernier** [comment]
This error happens on PVernier's laptop.

**Comment by pedrogit** [comment]
Did you try redefining the TT_ValidateTable() function? It's an ugly fix but does it work?

**Comment by prvernier** [comment]
The "ugly" fix seems to be working. I'll close the issue.

**Comment by pedrogit** [comment]
I'll keep it open as I have to find a better fix.
