### ISSUE TITLE
Test performance of engine using text only helper functions

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/PostgreSQL-Table-Translation-Framework#49]
* Once helper functions have been converted to accept pnly text (#47), test engine speed compared to beta release speed.
* We expect engine may be slower with text only helper functions because for every row that is translated, the engine has to convert the source values to text, then the helper function has to convert the text back to other types.
* If engine is much slower we might consider a different approach such as testing each helper function before it is used by calling it with default parameters. If error returned, we might assume the signature doesn't exist.

**Comment by edwardsmarc** [comment]
Initial test having implimented a text version of TT_FctEval took 15 minutes to translate 200 rows in ab_06. This is very slow. This was using the same translation attributes as the beta release.

**Comment by edwardsmarc** [comment]
Additional tests uing 200 rows of ab06 source table.

Translating CAS_ID attribute:
Text only engine - 59.5 secs
Beta release engine - <<1secs

Translating current ab06 table (34 attributes)
Text only engine - 14 mins
Beta release engine - 2.5 secs

**Comment by edwardsmarc** [comment]
* Issue was resolved by changing the query in TT_TextFctExists() that checks for loaded functions in the catalog.
* Updated engine using text only helper functions now runs about as fast as the release engine. Actually ran faster (5:27 mins) than the release engine (6:45 mins) for the entire AB06 translation on my laptop.
* I propose we continue using the text only helper function approach and further optimise the engine in other areas to further reduce run time. e.g. #29

**Comment by pedrogit** [comment]
To be closed?
