### ISSUE TITLE
Update TT_PadConcat and TT_Concat to accept strings of values

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/PostgreSQL-Table-Translation-Framework#52]
* Comma separated string approach should work once passed through TT_FctEval() in the engine. Implement and test with engine.
* Will allow a single signature for each function.

**Comment by edwardsmarc** [comment]
* I think TT_FctEval needs to be updated to support this.
* Current behaviour when receiving for example TT_Example('a,b,c', 'd,e,f') would be to feed look for columns named 'a,b,c', and 'd,e,f'. It won't find them so will supply 'a,b,c' and 'd,e,f' as values to the helper function.
* Desired behaviour is to look for columns a, b, and c, then return their respective values back as a comma separated string to the helper function, e.g. '1,2,3'.
* I'm still learning how TT_FctEval works but I expect we might need to add a nested loop to deal with comma separated values when evaluating arguments receieved from TT_ValidateTTables.

**Comment by edwardsmarc** [comment]
Proposal:
* Add if statement to TT_TextFctEval when looping through args.
* If arg string contains any commas, parse the arguments to get column names, run each column name through the rest of the TT_TextFctEval code: return values from json row or arg as string if it doesn't match a column name, wrap back into a comma separated string of values to pass to helper function.

**Comment by edwardsmarc** [comment]
* Implemented and tested.
* Engine now supports comma separated strings as inputs.
* If comma separated string detected while evaluating functions, the string is parsed to an array. If array elements are column names the value is returned, otherwise the element is returned. Resulting values are converted back to comma separated string and supplied to helper function.

**Comment by pedrogit** [comment]
What if there we need to provide a string with a comma inside?

**Comment by edwardsmarc** [comment]
We would either need to find a more complex way of identifying comma-separated lists of arguments, or not support column names and arguments that contain commas.

**Comment by pedrogit** [comment]
Normally this is fixed by providing an escape character like "\".

e.g. 'string\, with\, comma, string without comma'.

This ends up as two strings "string, with, comma" and "string without comma". 

So the parser must not treat comma preceded with "\" as separator.

Then the question is: What if I want a backslash before a comma. Answer: 'string\\, with\\, comma'

What if you want a backslash before the actual separating character? You can't...
