### ISSUE TITLE
TT_ValidateTTable - check return types match attribute type

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/PostgreSQL-Table-Translation-Framework#57]
* Currently TT_ValidateTTable loop through the translation table and returns a table of values accessible to the engine
  * target attribute
  * attribute type
  * an array of validation rules in the TT_RulesDef class allowing function name and args to be accessed by the engine.
  * translation rule in the TT_RulesDef class

Additional features:

* the return type of translation rules and the type of the error code should both match the attribute type

**Comment by edwardsmarc** [comment]
* Note we now check this in both the table validation (TT_ValidateTTable, #57) and in the engine (TT_Translate #67 ).

* Should we remove it from the engine?

**Comment by pedrogit** [comment]
I guess we could remove it from the engine.
