### ISSUE TITLE
TT_FctEval - add checkExistence parameter

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/PostgreSQL-Table-Translation-Framework#59]
* TT_Translate calls TT_FctEval to evaluate helper functions
* Currently TT_FctEval checks that the function exists using TT_FctExist
* However TT_ValidateTTable will also check function exists (#58 ) making the second check redundant.
* Make the TT_FctExists call in TT_FctEval optional and set it to FALSE in the call from the TT_Translate

**Comment by pedrogit** [comment]
I could say that the checkExistence parameter should be true by default.
