### ISSUE TITLE
helperFunctionTest.sql generates an error

### ISSUE THREAD

**Issue by prvernier** [edwardsmarc/PostgreSQL-Table-Translation-Framework#62]
ERROR:  function tt_map(text, text, text) is not unique
LINE 1246:        TT_Map('A'::text,'A,B,C,D'::text,'1,2,3,4'::text) = '...
                  ^
HINT:  Could not choose a best candidate function. You might need to add explicit type casts.
********** Error **********

ERROR: function tt_map(text, text, text) is not unique
SQL state: 42725
Hint: Could not choose a best candidate function. You might need to add explicit type casts.
Character: 56003

**Comment by edwardsmarc** [comment]
You might need to manually delete old functions from your database. Go to the public schema, click on Functions, manually delete all TT_ functions. Then try loading the engine again.

**Comment by edwardsmarc** [comment]
The problem is that these old function signatures are no longer in the uninstall file so they don't get removed.

**Comment by prvernier** [comment]
Okay, thanks. There's a lot of them and I guess there's no way to drop all TT functions in one fell swoop?

**Comment by edwardsmarc** [comment]
When you click on Functions it should show a list in the main window. You can select multiples and delete from the main window.

**Comment by prvernier** [comment]
Great, that was way quicker. The helperFunctionTest.sql now works properly. Issue closed!
