### ISSUE TITLE
Translation engine fails with ab16_avi01_lyr.csv (rule id: 3, 12, 14, 16, 18)

### ISSUE THREAD

**Issue by prvernier** [edwardsmarc/PostgreSQL-Table-Translation-Framework#64]
ERROR:  query string argument of EXECUTE is null
CONTEXT:  PL/pgSQL function _tt_translate(name,name,name,name,text[],boolean,integer,boolean,boolean) line 66 at EXECUTE
PL/pgSQL function tt_translate_ab16(name,name,name,name,text[],boolean,integer,boolean,boolean) line 3 at RETURN QUERY
********** Error **********

ERROR: query string argument of EXECUTE is null
SQL state: 22004
Context: PL/pgSQL function _tt_translate(name,name,name,name,text[],boolean,integer,boolean,boolean) line 66 at EXECUTE
PL/pgSQL function tt_translate_ab16(name,name,name,name,text[],boolean,integer,boolean,boolean) line 3 at RETURN QUERY

**Comment by edwardsmarc** [comment]
IsInt does not have an error code assigned. Try adding that and re-testing.

**Comment by prvernier** [comment]
The error only occurs with rule_id 12, 14, 16, 18 (same as the BC08 problem). The problem with rule_id 3 (structure_per) is that I was using the wrong attribute, so this is not an issue here anymore.
