### ISSUE TITLE
Review cases where there is no source value, but we return a target value

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/PostgreSQL-Table-Translation-Framework#66]
* AB16 LAYER attribute currently has validation rule set to false(|-8887), and translation set to copy(1)
* @prvernier - is the goal here to return a value of 1 in all rows?
* Currently it returns -8887 in all rows

* Easy solution - change validation to false(|1)
  * This is not ideal because we are using the validation rule as a translation function
* Better solution - add a TT_True validation function that skips validation and allows the translation rule to run on every row.
  * This is preferred because TT_Copy(1) can perform the translation

**Comment by prvernier** [comment]
The false(|1) validation function followed by the copy(1) translation function does solve the problem. However, like you mentioned, this may not be valid. So, a TT_True function would be good to have.

This situation does occur several times and, as well, it can be used as a placeholder while waiting a new rule or helper function.

**Comment by edwardsmarc** [comment]
Added TT_True()
