### ISSUE TITLE
Translation helper functions should handle all data types without crashing

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/PostgreSQL-Table-Translation-Framework#72]
What is the desired behavior if an invalid type is encountered?

e.g. if a non-numeric is passed to a function that returns int
* tt_copyint('1a'::text)

* Do we raise an error or return a NULL?
* If the translation table is written correctly this will be caught during validation, but we should still decide what to do in cases where invalid data makes it to the translation function.

**Comment by edwardsmarc** [comment]
* Edit all translation functions to validate input values and return ???? if invalid.
* Add this as a rule in the readMe custom helper functions list

**Comment by edwardsmarc** [comment]
@pedrogit - based on the error table (https://github.com/edwardsmarc/CASFRI/blob/master/docs/specifications/errors/cas_errors_specific.csv) I would expect we would return INVALID. What do you think?

**Comment by pedrogit** [comment]
Yes INVALID. My mistake. Bad paste. 

We will discuss that more thoroughly...
