### ISSUE TITLE
TT_ValidateTTable - check error types match attribute type

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/PostgreSQL-Table-Translation-Framework#76]
Error type should match attribute type in translation table. e.g. an integer targetAttributeType should not have "NULL" as an error. It should have e.g. -9999

**Comment by edwardsmarc** [comment]
* I propose we simply check the error code can be cast to the target attribute type.
* So a target attribute text type could still contain '-9999' as an error code (some users might want this).
* But an integer target type could not receive a string (e.g."NULL").

**Comment by pedrogit** [comment]
To be closed?
