### ISSUE TITLE
TT_Nothing() - what should this function return?

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/PostgreSQL-Table-Translation-Framework#77]
* Previous tables were using TT_Nothing() as a translation function placeholder in the translation tables where TT_False(|***) is supplied as a validation rule.
* Since TT_False always fails validation, TT_Nothing will never actually be called, but with updates to the validation of the translation table, we now need a placeholder function that:
  1. is defined in the catalog
  2. has a return type matching the attribute return type in the translation table

* Usually we would define TT_Nothing() as a VOID type to create a function that returns nothing. This doesn't work because it breaks rule 2 above.

* Create TT_NothingText(), TT_NothingDouble(), and TT_NothingInt() that return NULL. It doesn't matter what they return because they should never be called.

* We could just use TT_CopyText(''), TT_CopyDouble(0), and TT_CopyInt(0) as placeholders but this might be confusing.

**Comment by edwardsmarc** [comment]
* Made TT_NothingText, TT_NothingDouble, and TT_NothingInt.

* All return NULL.

**Comment by pedrogit** [comment]
Could we also have avoided to validate the return type when the translation function is TT_Nothing()?

**Comment by pedrogit** [comment]
Don't forget to document them in the readme. TT_NothingText(), TT_NothingDouble() and TT_NothingInt().

**Comment by edwardsmarc** [comment]
* I prefer keeping TT_NothingText(), TT_NothingDouble() and TT_NothingInt() as actual functions. They might be useful in other cases where NULL should be returned. It also avoids adding TT_Nothing() as a special case which would add another 'rule' for writing translation tables.
* @pedrogit @prvernier This is personal preference so I'm happy to defer if you disagree.

**Comment by pedrogit** [comment]
To be closed?
