### ISSUE TITLE
Make TT_GeoIntersects() validation function

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/PostgreSQL-Table-Translation-Framework#81]
* Should return true if geometry intersects with any polygons from the intersect table
* Otherwise return false

**Comment by pedrogit** [comment]
Should be simply TT_Intersects() and not sure it is necessary. We just have to make sure the associated translation rule return en error if it does not intersect.

This actually raise a flag, for certain type of error we could rely only on the translation rule. Not needing to validate the source value before. I'm wondering what are the condition that would make validation rules necessary if all translation rules report a proper error. We'll discuss that...

**Comment by edwardsmarc** [comment]
* Currently no translation rules return error codes. One advantage I see of keeping the error codes in the validation rules is that they are visible in the translation table and can be edited. Hard coded error codes cannot be edited by the user.
* This case might be an exception because running a geometry validation would be costly.

**Comment by pedrogit** [comment]
It is not necessarily more costly since the translation rule would not be executed if the validation fails. So I think we need it. I was in state of mind in which translation rules were able to return an error which is not the case (yet).

**Comment by pedrogit** [comment]
Actually to reflect the fact that this is a geo function and to follow PostGIS conventions it should be named TT_GeoIntersects() and the translation rule should be TT_GeoIntersection()
