### ISSUE TITLE
Evaluate the pros and cons of having translation rules able to handle and return errors.

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/PostgreSQL-Table-Translation-Framework#82]
This issue was raised by the many time we asked: What if no validation rule validates this kind of error in the source values?

Should the translation rules be made so that they can also handle and return errors? Right now only validation rules have error code associated with. What if some rules are not validated and that invalid values are passed to the translation rule?

If translation rules start handling errors, then what is the need for validation rules?

Should the translation rule just fail if it receive an invalid value without trying to figure a proper error code?

**Comment by edwardsmarc** [comment]
* One option could be for all translation rules to return a generic error code (e.g. 'TRANSLATION ERROR').
* This would be a flag for the user that a new validation function is needed.
* Hard coding all errors into the translation rules means that users can no longer use their own custom error systems which is a great feature.

**Comment by pedrogit** [comment]
The problem with 'TRANSLATION ERROR' is there is no clue as what was the error... We could return our own error codes, which cover most situations. There is no need to allows application developers to provide their own list of codes since these errors are translation file errors (there is a validation rule missing), no input data errors. They don't get written to the database (are they? Should the engine stop when encountering one?)

**Comment by edwardsmarc** [comment]
Summary of discussion:
* We can catch all errors and return a single generic translation error (e.g. TRANSLATION_ERROR or -3333) using BEGIN, EXCEPTION WHEN OTHERS as a wrapper around the translation function.
  * This will stop the engine crashing if it encounters an error.
  * Disadvantages:
    * Could be slow
    * Does not provide info about the error
* Alternative is to predict errors and catch them with specific error messages (e.g. null values, empty strings, out of range etc.). This is more informative for user and makes it easier to fix validation rules.
  * Disadvantage is an error that we have not caught will crash the engine. i.e. we need to predict all possible errors and catch them in the translation function code.

* We decide to test the generic wrapper option and see if it slows the engine. We can add specific error codes later if we think it is needed and we can catch them all.

* We will also log these errors in #48
* We also expect to add a stop, resume option when translation error is encountered. Similar to that expected for the validation functions.

**Comment by edwardsmarc** [comment]
Tests of translation functions after adding EXCEPTION block

CopyInt ----------------------------------------------------------------------------------16 seconds
CopyInt with EXCEPTION ---------------------------------------------------------------16 seconds
PadConcat -------------------------------------------------------------------------------15.5 seconds
PadConcat with EXCEPTION (no errors generated) ------------------------------------15.4 seconds
PadConcat with EXCEPTION (errors for all rows returned by EXCEPTION block) -----17 seconds

**Comment by edwardsmarc** [comment]
Current behaviour is to RAISE NOTICE for the errors we already had in any translation functions. Checking for Nulls or missing parameters for example. These are all things that should be caught by validation functions.

If the RAISE EXCEPTION block is triggered a RAISE NOTICE 'TRANSLATION_ERROR' is reported and the cell is RETURNed with either 'TRANSLATION_ERROR' or -3333.

**Comment by pedrogit** [comment]
There was no need to encapsulate the call to TT_TextFctEval() for translation rules in _TT_Translate() with an EXCEPTION block so that EVERY error produced by translation function would be catched? Now, if I'm right, we are catching only predicted errors.

**Comment by edwardsmarc** [comment]
I added the EXCEPTION blocks to each translation function. I guess adding it once to the TT_TextFctEval() call makes more sense.

**Comment by pedrogit** [comment]
I guess you will have to decide if you have to return a text or a int error code.
