### ISSUE TITLE
Some enhancements to the Helper Function documentation section in the readme

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/PostgreSQL-Table-Translation-Framework#83]
- I would remove the "Signatures" section when only one signature is possible.

- When more then one signature is possible, we should put the name of the parameter, not 'text'. The fact that everything is converted to text is an implementation detail that should not be known, or visible, to the translation file writer. Only to an eventual helper function writer. An extra signature that remove only a default parameter should not be considered an extra signature and be removed (I think it is always the case...). Signatures like this are useful when variants exists other than the ones created by using default parameters.

- We should sometimes be more explicit about the type of the parameter that has to be provided even if the functions accept text values. E.g. "min" and "max" must be numeric values. Another (better) way to do this is to provide the type before the name of the parameter in the function definition. e.g. Between(text srcVal, numeric min, numeric max, boolean includeMin[default TRUE], boolean includeMax[default TRUE]). Type could also simply be indicated in the description between parenthesis after the parameter name. e.g. Returns TRUE if srcVal (text) is between min (numeric) and max (numeric).

- We should sometimes indicate in which circonstances some helper functions are useful. E.g. HasUniqueValues, MatchTable, False, True. Why there are three version of Copy?

**Comment by edwardsmarc** [comment]
closed with #0589113bbb762f3076250c6aa842d05ce8439fef
