### ISSUE TITLE
Helper functions taking single quoted comma separated list of parameters should support commas and single quotes

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/PostgreSQL-Table-Translation-Framework#84]
Comma case: Concat('a,b, c,d', '-')

Where "a,b" is one string and "c,d" is another string to be concatenated with a dash resulting in 'a,b-c,d'

Single quote case: Concat('Let's', 'go', ' ')

The single quote case is easily fixed by supporting an escape character like backslash. e.g. Concat('Let\\'s', 'go', ' ')

The comma case can also be fixed the same way. e.g. Concat('a\\,b, c\\,d', '-')

**Comment by edwardsmarc** [comment]
Related to #93 

We need to distinguish:

YEAR - column name in source table where value (e.g. 2019) gets passed to helper function.

'YEAR' - string that gets passed to helper function

'YEAR, MONTH' - string of comma separated parameters where values (e.g. '2019, 06') get passed to helper function

''YEAR', 'MONTH'' - string of comma separated parameters where strings (e.g. 'YEAR, MONTH') get passed to helper function

''MONTH', MONTH' - mixed string of comma separated parameters where strings and values (e.g. 'MONTH, 06') get passed to helper function

''YEAR'\,'MONTH', YEAR\,MONTH' - mixed string of comma separated parameters with escape characters where strings and values (e.g. 'YEAR\,MONTH, 2019\,06') get passed to helper function
  * In this final case the helper functions would need to be updated to process the escape character.
