### ISSUE TITLE
Optionally stop and resume on validation error

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/PostgreSQL-Table-Translation-Framework#87]
When engine encounters an error in a validation function, it should optionally be able to stop and resume translation from the row causing the error.

**Comment by pedrogit** [comment]
The engine will stop in two cases at validation step:

- When a values is invalidated and the stopOnInvalid valid is set to TRUE as a parameter to TT_Translate() or as a parameter to a validation function.

- When an invalid paramater is passed to a validation function (this normally happen at the very beginning while validation the first row of values).

This was implemented as part of #141

Resume will be implemented as part of a future issue.
