### ISSUE TITLE
RAISE EXCEPTION in TT_ValidateTTable does not get passed through to TT_Translate

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/PostgreSQL-Table-Translation-Framework#89]
Errors raised in table validation function are not printed when the engine fails.
E.g. if a function is written wrong and doesn't exist in the catalog, running TT_ValidateTTable directly will print the message describing the missing function. When the engine is run using TT_Translate this message is not shown. How to pass the error message up to the higher level function?

**Comment by edwardsmarc** [comment]
* I guess you have turn debug on to get all the errors.
* @pedrogit Will users be expected to find error messages by turning debug on?

**Comment by pedrogit** [comment]
Where do you expect them to display? They should display in the message tab.

**Comment by edwardsmarc** [comment]
They only display if debug is turned on. Otherwise a different error gets displayed (from TT_Translate I guess). I'll do more investigation this week.

**Comment by edwardsmarc** [comment]
Closing. Solution is to turn debug on for error messages.
