### ISSUE TITLE
Engine should be able to distinguish strings from column names

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/PostgreSQL-Table-Translation-Framework#93]
* engine should be able to pass e.g. 'YEAR' as a string, and the value from the source table YEAR column within the same helper function.
 * alternative is setting a rule that lookup tables and source tables must have unique column names.
* e.g. a source table I'm working on and an intersect table both currently have the geometry stored in a column named wkb_geometry. The TT_GeoIntersectionText() function should be taking the intersect column name as a string - 'wkb_geometry'. But instead the value from the source table gets passed because the column names match.

* TT_ParseArgs should be updated to carry single quotes through from the translation table. Currently it strips quotes.
* TT_fctEvalText should be updated to flag quoted strings as string and differentiate them from column names.

* Possibly related to #84

**Comment by pedrogit** [comment]
One way is to force writters to reference to column names by surrounding them with braquets like "{" and "}". This ways we can continue not having to quote strings. Make sense?

**Comment by edwardsmarc** [comment]
Yes this makes sense. We will update TT_TextFctEval to flag strings starting in "{" and ending in "}" and pass them as strings, not as column names?

**Comment by pedrogit** [comment]
Isn't it the opposite? Just to make it clear: {year}, unquoted, would refer to a column name and year and 'year' would be the string 'year'.

**Comment by edwardsmarc** [comment]
Agreed.
I misread your suggestion but agree column names should use {}.

**Comment by edwardsmarc** [comment]
closed with branch merge e41c2fb7938ee4b166339b0831459a71d448691a

**Comment by edwardsmarc** [comment]
Reopening due to a new design:

We need to support column names, strings, comma separated strings of both column names and strings, and we need to be able to escape quotations inside strings.

We propose the following design:

1. Column names are printed as text but must be complete words and cannot contain any special characters. (e.g. column_A)
2. Strings are surrounded by single or double quotes (e.g. "str1" or 'str2')
3. Lists are surrounded by {}.
  * strings in a list are surrounded by single or double quotes {'str1', 'str2'}
  * strings containing commas in a list should be surrounded by quotes of a different type (e.g. {'str1', "str2,str3"} or {"str1", 'str2,str3'})
  * lists can contain both strings and column names (e.g. {column_A, 'str1', "str2,str3"})
4. Quotes needed inside strings should be escaped with \ (e.g. 'it\'s good' or {colA, 'str1', "it\'s, good"})
5. Quotes should support all other characters like spaces, @, / etc. (e.g. 'contact: name@email')

* We will need to carry quotes through ParseArgs so they can be ID'd by TextFctEval - https://www.regextester.com/3269
* We will need to support escape characters - https://stackoverflow.com/questions/249791/regex-for-quoted-string-with-escaping-quotes
* General help - https://www.postgresonline.com/journal/archives/152-Regular-Expressions-in-PostgreSQL.html

**Comment by pedrogit** [comment]
I precised the Column name specs.

**Comment by pedrogit** [comment]
4, 5 and 6 should be part of 2 so we end with only three rules for three different string types. Then we can copy these specs directly in the readme.

**Comment by edwardsmarc** [comment]
Here's my first attempt at a new parseArgs() line. This will pass the following as arguments to TextFctEval() which will replace any colnames with values then pass everything to the helper function:
* column names that are words and can also contain - or .
* strings with single quotes that can contain anything
* strings with double quotes that can contain anything
* lists of arguments in curly brackets. The entire list would get passed as is to TextFctEval() which would identify column names and replace them with values from the source table.

This should run in sql and return a row for each argument that gets passed to TextFctEval():
SELECT regexp_matches('column-B, ''str i/-ng1'', "s tr-ing@2", {colA, colB, ''col@C'', "co lD"}', '([-\.''"\w]+|''[^'']+''|"[^"]+"|{.+})', 'g')

Note that any incorrect column names containing a space for example would get split in two and result in too many arguments being passed to the helper. e.g. SELECT regexp_matches('column B,', '([-\.''"\w]+|''[^'']+''|"[^"]+"|{.+})', 'g').

This would be caught during translation table validation if checkExistence = TRUE.

It could however slip through in cases where the function has multiple signatures.

**Comment by pedrogit** [comment]
Note that underscore is supported for column names. I don't know about dash (-) and point (.).

What about:

SELECT regexp_matches(' co_lumn-B, column  B , ''str i/-ng1'', "s tr-ing@2" , {colA, colB, ''col@C'', "co lD"}', 
				        '([^\s,][_\-\w\s]*|''[^'']+''|"[^"]+"|{.+})', 'g')

You could then search for spaces in column names and report an error if some are found.

**Comment by edwardsmarc** [comment]
Great! That's what I was trying to do. 

Next question is where do we check the column names for spaces? I'd say in TT_ValidateTTable, that way it only has to be done once, not for every row during translation. We could change the checkExistence argument to something more generic like validateHelpers. If that flag is TRUE then we check the helper function exists, and check the column names are valid.

**Comment by pedrogit** [comment]
parseArgs() should not return invalid values. If it find a column name with spaces it should RAISE EXCEPTION right away.

**Comment by pedrogit** [comment]
I suggest you create a TT_ParseStringList() also so we can reuse it when splitting arguments passed to TT_MapText() and TT_Concat() instead of the too simple string_to_array() which does not support commas inside quotes and escaped quotes.

**Comment by pedrogit** [comment]
Probably we can remove the "Known issues" section from the readme after that...
