### ISSUE TITLE
Make conversion scripts attempt to validate geometries during/after loading

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/PostgreSQL-Table-Translation-Framework#95]
* Helper functions dealing with geometries can validate the source geometries and attempt to fix geometries for each row that is processed. We currently do this in TT_GeoIntersectionText for example.

* Non-source tables such as intersect tables (e.g. photo year) are trickier to validate, we don't currently have an easy way to do this inside the engine.

* Solution seems to be that the intersect tables should be valid before running the engine.

* We could simply state that users are responsible for having valid intersect tables before running the engine. 

* For CASFRI, we could attempt to make them valid on loading using gdal to run some sql code.

* Related to #94

**Comment by pedrogit** [comment]
Validating and fixing source geometries is mandatory. That was a big part of cas_04. 

Now since we never try to fix input values with validation rules, we could systematically fix them with a translation rule e.g. TT_MakeValid({geom}) and do nothing at validation. TT_MakeValid() would simply return valid geometries and fix broken ones. That one very rare case where we can fix input values without entering into complex analysis.

**Comment by edwardsmarc** [comment]
Should this function overwrite the existing geometry or add a second, fixed geometry column?

**Comment by pedrogit** [comment]
Normally ST_MakeValid() does not change the geometry if it's valid. So it should replace the geometry.

Our own function should first check with ST_IsValid() and call ST_MakeValid() only if it's unvalid.

**Comment by edwardsmarc** [comment]
Do we agree that ST_MakeValid() cannot be used to fix geometies inside the engine?

The reason is that this would only fix geometries in the **target table**. Subsequent translations will still need valid geometries from the **source table**.

We could fix the geometries inside the helper functions each time but this seems redundant.

Better might be to validate and fix source geometries before translation using:
https://github.com/edwardsmarc/CASFRI/issues/103
